// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ethermint/nameservice/v1/nameservice.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the nameservice module parameters
type Params struct {
	RecordRent                      types.Coin    `protobuf:"bytes,1,opt,name=record_rent,json=recordRent,proto3" json:"record_rent" json:"record_rent" yaml:"record_rent"`
	RecordRentDuration              time.Duration `protobuf:"bytes,2,opt,name=record_rent_duration,json=recordRentDuration,proto3,stdduration" json:"record_rent_duration" json:"record_rent_duration" yaml:"record_rent_duration"`
	AuthorityRent                   types.Coin    `protobuf:"bytes,3,opt,name=authority_rent,json=authorityRent,proto3" json:"authority_rent" json:"authority_rent" yaml:"authority_rent"`
	AuthorityRentDuration           time.Duration `protobuf:"bytes,4,opt,name=authority_rent_duration,json=authorityRentDuration,proto3,stdduration" json:"authority_rent_duration" json:"authority_rent_duration" yaml:"authority_rent_duration"`
	AuthorityGracePeriod            time.Duration `protobuf:"bytes,5,opt,name=authority_grace_period,json=authorityGracePeriod,proto3,stdduration" json:"authority_grace_period" json:"authority_grace_period" yaml:"authority_grace_period"`
	AuthorityAuctionEnabled         bool          `protobuf:"varint,6,opt,name=authority_auction_enabled,json=authorityAuctionEnabled,proto3" json:"authority_auction_enabled,omitempty" json:"authority_auction_enabled" yaml:"authority_auction_enabled"`
	AuthorityAuctionCommitsDuration time.Duration `protobuf:"bytes,7,opt,name=authority_auction_commits_duration,json=authorityAuctionCommitsDuration,proto3,stdduration" json:"authority_auction_commits_duration" json:"authority_auction_commits_duration" yaml:"authority_auction_commits_duration"`
	AuthorityAuctionRevealsDuration time.Duration `protobuf:"bytes,8,opt,name=authority_auction_reveals_duration,json=authorityAuctionRevealsDuration,proto3,stdduration" json:"authority_auction_reveals_duration" json:"authority_auction_reveals_duration" yaml:"authority_auction_reveals_duration"`
	AuthorityAuctionCommitFee       types.Coin    `protobuf:"bytes,9,opt,name=authority_auction_commit_fee,json=authorityAuctionCommitFee,proto3" json:"authority_auction_commit_fee" json:"authority_auction_commit_fee" yaml:"authority_auction_commit_fee"`
	AuthorityAuctionRevealFee       types.Coin    `protobuf:"bytes,10,opt,name=authority_auction_reveal_fee,json=authorityAuctionRevealFee,proto3" json:"authority_auction_reveal_fee" json:"authority_auction_reveal_fee" yaml:"authority_auction_reveal_fee"`
	AuthorityAuctionMinimumBid      types.Coin    `protobuf:"bytes,11,opt,name=authority_auction_minimum_bid,json=authorityAuctionMinimumBid,proto3" json:"authority_auction_minimum_bid" json:"authority_auction_minimum_bid" yaml:"authority_auction_minimum_bid"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_efa8414b7a9dab9d, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetRecordRent() types.Coin {
	if m != nil {
		return m.RecordRent
	}
	return types.Coin{}
}

func (m *Params) GetRecordRentDuration() time.Duration {
	if m != nil {
		return m.RecordRentDuration
	}
	return 0
}

func (m *Params) GetAuthorityRent() types.Coin {
	if m != nil {
		return m.AuthorityRent
	}
	return types.Coin{}
}

func (m *Params) GetAuthorityRentDuration() time.Duration {
	if m != nil {
		return m.AuthorityRentDuration
	}
	return 0
}

func (m *Params) GetAuthorityGracePeriod() time.Duration {
	if m != nil {
		return m.AuthorityGracePeriod
	}
	return 0
}

func (m *Params) GetAuthorityAuctionEnabled() bool {
	if m != nil {
		return m.AuthorityAuctionEnabled
	}
	return false
}

func (m *Params) GetAuthorityAuctionCommitsDuration() time.Duration {
	if m != nil {
		return m.AuthorityAuctionCommitsDuration
	}
	return 0
}

func (m *Params) GetAuthorityAuctionRevealsDuration() time.Duration {
	if m != nil {
		return m.AuthorityAuctionRevealsDuration
	}
	return 0
}

func (m *Params) GetAuthorityAuctionCommitFee() types.Coin {
	if m != nil {
		return m.AuthorityAuctionCommitFee
	}
	return types.Coin{}
}

func (m *Params) GetAuthorityAuctionRevealFee() types.Coin {
	if m != nil {
		return m.AuthorityAuctionRevealFee
	}
	return types.Coin{}
}

func (m *Params) GetAuthorityAuctionMinimumBid() types.Coin {
	if m != nil {
		return m.AuthorityAuctionMinimumBid
	}
	return types.Coin{}
}

// Params defines the nameservice module records
type Record struct {
	Id         string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" json:"id" yaml:"id"`
	BondId     string    `protobuf:"bytes,2,opt,name=bond_id,json=bondId,proto3" json:"bond_id,omitempty" json:"bondId" yaml:"bondId"`
	CreateTime time.Time `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3,stdtime" json:"create_time" json:"createTime" yaml:"createTime"`
	ExpiryTime time.Time `protobuf:"bytes,4,opt,name=expiry_time,json=expiryTime,proto3,stdtime" json:"expiry_time" json:"expiryTime" yaml:"expiryTime"`
	Deleted    bool      `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Owners     []string  `protobuf:"bytes,6,rep,name=owners,proto3" json:"owners,omitempty" json:"owners" yaml:"owners"`
	Attributes []byte    `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty" json:"attributes" yaml:"attributes"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_efa8414b7a9dab9d, []int{1}
}
func (m *Record) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Record.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return m.Size()
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Record) GetBondId() string {
	if m != nil {
		return m.BondId
	}
	return ""
}

func (m *Record) GetCreateTime() time.Time {
	if m != nil {
		return m.CreateTime
	}
	return time.Time{}
}

func (m *Record) GetExpiryTime() time.Time {
	if m != nil {
		return m.ExpiryTime
	}
	return time.Time{}
}

func (m *Record) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Record) GetOwners() []string {
	if m != nil {
		return m.Owners
	}
	return nil
}

func (m *Record) GetAttributes() []byte {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// AuthorityEntry defines the nameservice module AuthorityEntries
type AuthorityEntry struct {
	Name   string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" json:"name" yaml:"name"`
	Record *NameAuthority `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
}

func (m *AuthorityEntry) Reset()         { *m = AuthorityEntry{} }
func (m *AuthorityEntry) String() string { return proto.CompactTextString(m) }
func (*AuthorityEntry) ProtoMessage()    {}
func (*AuthorityEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_efa8414b7a9dab9d, []int{2}
}
func (m *AuthorityEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuthorityEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuthorityEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuthorityEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorityEntry.Merge(m, src)
}
func (m *AuthorityEntry) XXX_Size() int {
	return m.Size()
}
func (m *AuthorityEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorityEntry.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorityEntry proto.InternalMessageInfo

func (m *AuthorityEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AuthorityEntry) GetRecord() *NameAuthority {
	if m != nil {
		return m.Record
	}
	return nil
}

type NameAuthority struct {
	// Owner public key.
	OwnerPublicKey string `protobuf:"bytes,1,opt,name=owner_public_key,json=ownerPublicKey,proto3" json:"owner_public_key,omitempty" json:"ownerPublicKey" yaml:"ownerPublicKey"`
	// Owner address.
	OwnerAddress string `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty" json:"ownerAddress" yaml:"ownerAddress"`
	// height at which name/authority was created.
	Height     uint64        `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Status     string        `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	AuctionId  string        `protobuf:"bytes,5,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty" json:"auctionID" yaml:"auctionID"`
	BondId     string        `protobuf:"bytes,6,opt,name=bond_id,json=bondId,proto3" json:"bond_id,omitempty" json:"bondID" yaml:"bondID"`
	ExpiryTime time.Duration `protobuf:"bytes,7,opt,name=expiry_time,json=expiryTime,proto3,stdduration" json:"expiry_time" json:"expiryTime" yaml:"expiryTime"`
}

func (m *NameAuthority) Reset()         { *m = NameAuthority{} }
func (m *NameAuthority) String() string { return proto.CompactTextString(m) }
func (*NameAuthority) ProtoMessage()    {}
func (*NameAuthority) Descriptor() ([]byte, []int) {
	return fileDescriptor_efa8414b7a9dab9d, []int{3}
}
func (m *NameAuthority) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NameAuthority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NameAuthority.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NameAuthority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameAuthority.Merge(m, src)
}
func (m *NameAuthority) XXX_Size() int {
	return m.Size()
}
func (m *NameAuthority) XXX_DiscardUnknown() {
	xxx_messageInfo_NameAuthority.DiscardUnknown(m)
}

var xxx_messageInfo_NameAuthority proto.InternalMessageInfo

func (m *NameAuthority) GetOwnerPublicKey() string {
	if m != nil {
		return m.OwnerPublicKey
	}
	return ""
}

func (m *NameAuthority) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *NameAuthority) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *NameAuthority) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *NameAuthority) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

func (m *NameAuthority) GetBondId() string {
	if m != nil {
		return m.BondId
	}
	return ""
}

func (m *NameAuthority) GetExpiryTime() time.Duration {
	if m != nil {
		return m.ExpiryTime
	}
	return 0
}

// NameEntry
type NameEntry struct {
	Name   string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" json:"name" yaml:"name"`
	Record *NameRecord `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
}

func (m *NameEntry) Reset()         { *m = NameEntry{} }
func (m *NameEntry) String() string { return proto.CompactTextString(m) }
func (*NameEntry) ProtoMessage()    {}
func (*NameEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_efa8414b7a9dab9d, []int{4}
}
func (m *NameEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NameEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NameEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NameEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameEntry.Merge(m, src)
}
func (m *NameEntry) XXX_Size() int {
	return m.Size()
}
func (m *NameEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_NameEntry.DiscardUnknown(m)
}

var xxx_messageInfo_NameEntry proto.InternalMessageInfo

func (m *NameEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NameEntry) GetRecord() *NameRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

// NameRecord
type NameRecord struct {
	Latest  *NameRecordEntry   `protobuf:"bytes,1,opt,name=latest,proto3" json:"latest,omitempty"`
	History []*NameRecordEntry `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
}

func (m *NameRecord) Reset()         { *m = NameRecord{} }
func (m *NameRecord) String() string { return proto.CompactTextString(m) }
func (*NameRecord) ProtoMessage()    {}
func (*NameRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_efa8414b7a9dab9d, []int{5}
}
func (m *NameRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NameRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NameRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NameRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameRecord.Merge(m, src)
}
func (m *NameRecord) XXX_Size() int {
	return m.Size()
}
func (m *NameRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_NameRecord.DiscardUnknown(m)
}

var xxx_messageInfo_NameRecord proto.InternalMessageInfo

func (m *NameRecord) GetLatest() *NameRecordEntry {
	if m != nil {
		return m.Latest
	}
	return nil
}

func (m *NameRecord) GetHistory() []*NameRecordEntry {
	if m != nil {
		return m.History
	}
	return nil
}

// NameRecordEntry
type NameRecordEntry struct {
	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Height uint64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *NameRecordEntry) Reset()         { *m = NameRecordEntry{} }
func (m *NameRecordEntry) String() string { return proto.CompactTextString(m) }
func (*NameRecordEntry) ProtoMessage()    {}
func (*NameRecordEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_efa8414b7a9dab9d, []int{6}
}
func (m *NameRecordEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NameRecordEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NameRecordEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NameRecordEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameRecordEntry.Merge(m, src)
}
func (m *NameRecordEntry) XXX_Size() int {
	return m.Size()
}
func (m *NameRecordEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_NameRecordEntry.DiscardUnknown(m)
}

var xxx_messageInfo_NameRecordEntry proto.InternalMessageInfo

func (m *NameRecordEntry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NameRecordEntry) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// Signature
type Signature struct {
	Sig    string `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty" json:"sig" yaml:"sig"`
	PubKey string `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty" json:"pubKey" yaml:"pubKey"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_efa8414b7a9dab9d, []int{7}
}
func (m *Signature) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return m.Size()
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSig() string {
	if m != nil {
		return m.Sig
	}
	return ""
}

func (m *Signature) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "ethermint.nameservice.v1.Params")
	proto.RegisterType((*Record)(nil), "ethermint.nameservice.v1.Record")
	proto.RegisterType((*AuthorityEntry)(nil), "ethermint.nameservice.v1.AuthorityEntry")
	proto.RegisterType((*NameAuthority)(nil), "ethermint.nameservice.v1.NameAuthority")
	proto.RegisterType((*NameEntry)(nil), "ethermint.nameservice.v1.NameEntry")
	proto.RegisterType((*NameRecord)(nil), "ethermint.nameservice.v1.NameRecord")
	proto.RegisterType((*NameRecordEntry)(nil), "ethermint.nameservice.v1.NameRecordEntry")
	proto.RegisterType((*Signature)(nil), "ethermint.nameservice.v1.Signature")
}

func init() {
	proto.RegisterFile("ethermint/nameservice/v1/nameservice.proto", fileDescriptor_efa8414b7a9dab9d)
}

var fileDescriptor_efa8414b7a9dab9d = []byte{
	// 1168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4d, 0x73, 0xdb, 0xc4,
	0x1b, 0x8f, 0xe2, 0xfc, 0x95, 0x7a, 0xd3, 0xe4, 0xcf, 0x2c, 0x69, 0xe3, 0xa4, 0x60, 0x05, 0x43,
	0x27, 0x85, 0x0c, 0x12, 0xa1, 0x87, 0xf2, 0x3a, 0x4c, 0x9c, 0x84, 0x4c, 0x60, 0x80, 0xb0, 0xe5,
	0x02, 0x17, 0x8d, 0x64, 0x6d, 0xed, 0x05, 0x4b, 0xf2, 0xec, 0xae, 0x42, 0xcd, 0x0d, 0x3e, 0x41,
	0x0e, 0x1c, 0x72, 0xe0, 0x1b, 0x70, 0xe0, 0x63, 0xd0, 0x63, 0x8f, 0x0c, 0x33, 0x18, 0x26, 0xf9,
	0x06, 0xfe, 0x04, 0x8c, 0x76, 0x57, 0x5a, 0x49, 0xb6, 0x6b, 0x4a, 0xb9, 0xed, 0x3e, 0x2f, 0xbf,
	0xe7, 0xf7, 0x3c, 0xfb, 0x3c, 0xab, 0x15, 0x78, 0x0d, 0xf3, 0x1e, 0xa6, 0x21, 0x89, 0xb8, 0x13,
	0x79, 0x21, 0x66, 0x98, 0x9e, 0x91, 0x0e, 0x76, 0xce, 0xf6, 0x8a, 0x5b, 0x7b, 0x40, 0x63, 0x1e,
	0xc3, 0x46, 0x6e, 0x6b, 0x17, 0x95, 0x67, 0x7b, 0x5b, 0xcd, 0x6e, 0x1c, 0x77, 0xfb, 0xd8, 0x11,
	0x76, 0x7e, 0xf2, 0xc0, 0x09, 0x12, 0xea, 0x71, 0x12, 0x47, 0xd2, 0x73, 0xcb, 0xaa, 0xea, 0x39,
	0x09, 0x31, 0xe3, 0x5e, 0x38, 0x50, 0x06, 0xeb, 0xdd, 0xb8, 0x1b, 0x8b, 0xa5, 0x93, 0xae, 0x94,
	0xb4, 0xd9, 0x89, 0x59, 0x18, 0x33, 0xc7, 0xf7, 0x58, 0x4a, 0xc9, 0xc7, 0xdc, 0xdb, 0x73, 0x3a,
	0x31, 0x51, 0xb0, 0xad, 0x3f, 0x56, 0x81, 0x79, 0xea, 0x51, 0x2f, 0x64, 0x90, 0x80, 0x15, 0x8a,
	0x3b, 0x31, 0x0d, 0x5c, 0x8a, 0x23, 0xde, 0x30, 0xb6, 0x8d, 0x3b, 0x2b, 0x6f, 0x6e, 0xda, 0x12,
	0xc0, 0x4e, 0x01, 0x6c, 0x05, 0x60, 0x1f, 0xc4, 0x24, 0x6a, 0xbf, 0xfe, 0x68, 0x64, 0x2d, 0x8c,
	0x47, 0xd6, 0xed, 0xaf, 0x59, 0x1c, 0xbd, 0xd3, 0x2a, 0xf8, 0xb6, 0xb6, 0x87, 0x5e, 0xd8, 0x2f,
	0x8b, 0x10, 0x90, 0x3b, 0x84, 0x23, 0x0e, 0xcf, 0x0d, 0xb0, 0x5e, 0x50, 0xba, 0x59, 0xae, 0x8d,
	0x45, 0x15, 0x54, 0x26, 0x6b, 0x67, 0xc9, 0xda, 0x87, 0xca, 0xa0, 0x7d, 0xa0, 0x82, 0xde, 0x9b,
	0x08, 0x9a, 0x83, 0x4c, 0x89, 0xae, 0x75, 0x17, 0x7f, 0x5a, 0x06, 0x82, 0x9a, 0x4a, 0x06, 0x0c,
	0x13, 0xb0, 0xe6, 0x25, 0xbc, 0x17, 0x53, 0xc2, 0x87, 0xb2, 0x00, 0xb5, 0x79, 0x05, 0xb8, 0xab,
	0xb8, 0xec, 0x4a, 0x2e, 0x65, 0xf7, 0x8c, 0x45, 0x45, 0x8a, 0x56, 0x73, 0x81, 0xa8, 0xc4, 0x4f,
	0x06, 0xd8, 0x28, 0x9b, 0xe8, 0x62, 0x2c, 0xcd, 0x2b, 0xc6, 0x89, 0x22, 0xf0, 0xfe, 0x34, 0x02,
	0x13, 0xf5, 0x98, 0xa5, 0x16, 0x25, 0xb9, 0x51, 0xa2, 0x95, 0x57, 0xe5, 0xc2, 0x00, 0x37, 0xb5,
	0x5f, 0x97, 0x7a, 0x1d, 0xec, 0x0e, 0x30, 0x25, 0x71, 0xd0, 0xf8, 0xdf, 0x3c, 0x76, 0xc7, 0x8a,
	0xdd, 0xbb, 0x55, 0x76, 0x45, 0x98, 0x49, 0x72, 0x25, 0xad, 0xe0, 0xb6, 0x9e, 0x2b, 0x8f, 0x53,
	0xdd, 0xa9, 0x50, 0xc1, 0xef, 0x0d, 0xb0, 0xa9, 0xbd, 0xbc, 0xa4, 0x93, 0x06, 0x75, 0x71, 0xe4,
	0xf9, 0x7d, 0x1c, 0x34, 0xcc, 0x6d, 0xe3, 0xce, 0xb5, 0xf6, 0xd1, 0x78, 0x64, 0xed, 0x57, 0xc3,
	0x57, 0x4c, 0x27, 0x19, 0x54, 0x0d, 0x90, 0x3e, 0xa1, 0x7d, 0xa9, 0x3a, 0x92, 0x1a, 0xf8, 0xab,
	0x01, 0xa6, 0xf8, 0x75, 0xe2, 0x30, 0x24, 0x9c, 0xe9, 0x83, 0x5c, 0x9e, 0x57, 0x2a, 0x57, 0x95,
	0xea, 0xfe, 0x2c, 0xae, 0x55, 0xc8, 0xd9, 0xa4, 0x27, 0x2c, 0x45, 0x09, 0xad, 0x6a, 0x06, 0x07,
	0xd2, 0x2c, 0x3f, 0xe8, 0xe9, 0x99, 0x50, 0x7c, 0x86, 0xbd, 0x7e, 0x21, 0x93, 0x6b, 0xcf, 0x9c,
	0x49, 0x15, 0x72, 0x76, 0x26, 0x13, 0x96, 0xd3, 0x33, 0x41, 0xd2, 0x2c, 0xcf, 0xe4, 0x67, 0x03,
	0xbc, 0x30, 0xab, 0x2c, 0xee, 0x03, 0x8c, 0x1b, 0xf5, 0x79, 0x73, 0xfd, 0x99, 0xca, 0xe1, 0xf8,
	0xc9, 0xa7, 0x91, 0x82, 0xcd, 0x3b, 0x07, 0x61, 0x83, 0x36, 0xa7, 0x57, 0xff, 0x43, 0x8c, 0x67,
	0xb0, 0x95, 0xa9, 0x0b, 0xb6, 0xe0, 0x99, 0xd9, 0x6a, 0xb0, 0x79, 0xb5, 0x9e, 0xc1, 0x56, 0x56,
	0x38, 0x65, 0xfb, 0x8b, 0x01, 0x5e, 0x9c, 0x74, 0x0e, 0x49, 0x44, 0xc2, 0x24, 0x74, 0x7d, 0x12,
	0x34, 0x56, 0xe6, 0xd1, 0xfd, 0x5c, 0xd1, 0x3d, 0x99, 0x45, 0xb7, 0x80, 0x36, 0x9b, 0x6f, 0xd1,
	0x08, 0x6d, 0x55, 0x09, 0x7f, 0x22, 0xb5, 0x6d, 0x12, 0xb4, 0xae, 0x6a, 0xc0, 0x44, 0xe2, 0xb6,
	0x87, 0x3b, 0x60, 0x91, 0x04, 0xe2, 0xb3, 0x56, 0x6f, 0x6f, 0x8c, 0x47, 0xd6, 0xf3, 0x92, 0x81,
	0x0e, 0x93, 0x62, 0x2d, 0x92, 0x00, 0xbe, 0x05, 0x96, 0xfd, 0x38, 0x0a, 0x5c, 0x12, 0x88, 0xef,
	0x51, 0xbd, 0x6d, 0x8d, 0x47, 0xd6, 0x2d, 0x69, 0x9d, 0x2a, 0x4e, 0x72, 0x0f, 0xb5, 0x43, 0xa6,
	0x5c, 0xc0, 0x3e, 0x58, 0xe9, 0x50, 0xec, 0x71, 0xec, 0xa6, 0x5f, 0x67, 0xf5, 0x05, 0xd9, 0x9a,
	0x98, 0x96, 0x2f, 0xb2, 0x4f, 0x77, 0xdb, 0x51, 0xd5, 0x78, 0x59, 0xa2, 0x4b, 0xe7, 0x54, 0x9d,
	0x45, 0x28, 0x48, 0xce, 0xd3, 0xf6, 0x07, 0x5a, 0x90, 0x46, 0xc3, 0x0f, 0x07, 0x84, 0x0e, 0x65,
	0xb4, 0xa5, 0xa7, 0x8d, 0x26, 0x9d, 0x8b, 0xd1, 0x0a, 0x12, 0x19, 0x4d, 0x0b, 0x60, 0x03, 0x2c,
	0x07, 0xb8, 0x8f, 0x39, 0x96, 0x57, 0xff, 0x35, 0x94, 0x6d, 0xe1, 0x3d, 0x60, 0xc6, 0xdf, 0x46,
	0x98, 0xb2, 0x86, 0xb9, 0x5d, 0x2b, 0x97, 0x4b, 0xca, 0x33, 0x78, 0xb5, 0x43, 0xca, 0x1c, 0x1e,
	0x03, 0xe0, 0x71, 0x4e, 0x89, 0x9f, 0x70, 0xcc, 0xc4, 0x2d, 0x79, 0xbd, 0xbd, 0xa3, 0xf9, 0x69,
	0x5d, 0xde, 0x08, 0x5a, 0x82, 0x0a, 0xae, 0xad, 0x1f, 0x0c, 0xb0, 0xb6, 0x9f, 0x35, 0xc1, 0x51,
	0xc4, 0xe9, 0x10, 0x3a, 0x60, 0x29, 0x7d, 0x61, 0xa9, 0xf3, 0xbe, 0x35, 0x1e, 0x59, 0x1b, 0x12,
	0x35, 0x95, 0x66, 0x78, 0x62, 0x8d, 0x84, 0x21, 0xfc, 0x00, 0x98, 0xf2, 0x59, 0xa0, 0x1e, 0x21,
	0x3b, 0xf6, 0xac, 0xb7, 0x9a, 0xfd, 0xa9, 0x17, 0xe2, 0x3c, 0x1c, 0x52, 0x6e, 0xad, 0xdf, 0x6b,
	0x60, 0xb5, 0xa4, 0x81, 0x5f, 0x82, 0xe7, 0x44, 0xa6, 0xee, 0x20, 0xf1, 0xfb, 0xa4, 0xe3, 0x7e,
	0x83, 0x87, 0x8a, 0x8f, 0xa3, 0x9f, 0x0d, 0xc2, 0xe2, 0x54, 0x18, 0x7c, 0x8c, 0x87, 0xa5, 0x52,
	0x69, 0x29, 0x5a, 0x2b, 0x0b, 0xe0, 0x29, 0x58, 0x95, 0xd0, 0x5e, 0x10, 0x50, 0xcc, 0x98, 0xea,
	0xd4, 0xdd, 0xf1, 0xc8, 0xda, 0x29, 0xe0, 0xee, 0x4b, 0x6d, 0x09, 0x35, 0x93, 0xa1, 0xeb, 0xc5,
	0x2d, 0xbc, 0x09, 0xcc, 0x1e, 0x26, 0xdd, 0x9e, 0x7c, 0xf8, 0x2c, 0x21, 0xb5, 0x4b, 0xe5, 0x8c,
	0x7b, 0x3c, 0x61, 0xa2, 0xc1, 0xea, 0x48, 0xed, 0xe0, 0x21, 0x00, 0xd9, 0x34, 0x12, 0xd9, 0x12,
	0xf5, 0xf6, 0xed, 0xf1, 0xc8, 0x7a, 0x29, 0x1b, 0x6c, 0xa1, 0x3b, 0x39, 0xd4, 0x43, 0x9c, 0x09,
	0x50, 0x3d, 0x5b, 0x97, 0x66, 0xcd, 0x9c, 0x3a, 0x6b, 0x87, 0xa5, 0x59, 0x3b, 0x2c, 0xcd, 0x5a,
	0xb1, 0xfb, 0x97, 0xff, 0xd3, 0xee, 0xbf, 0xa8, 0x74, 0x7f, 0xeb, 0x3b, 0x50, 0x4f, 0xcf, 0xf6,
	0x5f, 0xf6, 0xd6, 0x7b, 0x95, 0xde, 0x7a, 0xe5, 0xc9, 0xbd, 0x25, 0x2f, 0xac, 0xbc, 0xb1, 0x7e,
	0x34, 0x00, 0xd0, 0x62, 0xb8, 0x0f, 0xcc, 0xbe, 0xc7, 0x31, 0xcb, 0x9e, 0xe8, 0xaf, 0xfe, 0x13,
	0x30, 0x41, 0x1c, 0x29, 0x47, 0x78, 0x00, 0x96, 0x7b, 0x84, 0xf1, 0x98, 0x0e, 0x1b, 0x8b, 0xdb,
	0xb5, 0xa7, 0xc3, 0xc8, 0x3c, 0x5b, 0x6f, 0x83, 0xff, 0x57, 0x74, 0x70, 0x4d, 0x5f, 0xb1, 0xe2,
	0x26, 0xd5, 0x3d, 0xb5, 0x58, 0xec, 0xa9, 0x16, 0x05, 0xf5, 0xfb, 0xa4, 0x1b, 0x79, 0x3c, 0xa1,
	0x18, 0xee, 0x82, 0x1a, 0x23, 0x5d, 0x55, 0xcc, 0xcd, 0xf1, 0xc8, 0xba, 0x21, 0x8b, 0xc9, 0x48,
	0x37, 0xab, 0x65, 0xba, 0x44, 0xa9, 0x55, 0xda, 0x2f, 0x83, 0xc4, 0x17, 0x93, 0x34, 0x71, 0x37,
	0x0f, 0x12, 0xbf, 0x30, 0x41, 0x6a, 0x87, 0x4c, 0xb9, 0x68, 0x7f, 0xf4, 0xe8, 0xb2, 0x69, 0x3c,
	0xbe, 0x6c, 0x1a, 0x7f, 0x5d, 0x36, 0x8d, 0xf3, 0xab, 0xe6, 0xc2, 0xe3, 0xab, 0xe6, 0xc2, 0x6f,
	0x57, 0xcd, 0x85, 0xaf, 0xde, 0xe8, 0x12, 0xde, 0x4b, 0x7c, 0xbb, 0x13, 0x87, 0x0e, 0xef, 0x79,
	0x94, 0x11, 0xe6, 0xe8, 0x7f, 0xba, 0x87, 0xa5, 0xbf, 0x3a, 0x3e, 0x1c, 0x60, 0xe6, 0x9b, 0xa2,
	0xbd, 0xee, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x16, 0xc6, 0xdf, 0x61, 0xfb, 0x0d, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AuthorityAuctionMinimumBid.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintNameservice(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	{
		size, err := m.AuthorityAuctionRevealFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintNameservice(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size, err := m.AuthorityAuctionCommitFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintNameservice(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	n4, err4 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.AuthorityAuctionRevealsDuration, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.AuthorityAuctionRevealsDuration):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintNameservice(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x42
	n5, err5 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.AuthorityAuctionCommitsDuration, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.AuthorityAuctionCommitsDuration):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintNameservice(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x3a
	if m.AuthorityAuctionEnabled {
		i--
		if m.AuthorityAuctionEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	n6, err6 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.AuthorityGracePeriod, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.AuthorityGracePeriod):])
	if err6 != nil {
		return 0, err6
	}
	i -= n6
	i = encodeVarintNameservice(dAtA, i, uint64(n6))
	i--
	dAtA[i] = 0x2a
	n7, err7 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.AuthorityRentDuration, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.AuthorityRentDuration):])
	if err7 != nil {
		return 0, err7
	}
	i -= n7
	i = encodeVarintNameservice(dAtA, i, uint64(n7))
	i--
	dAtA[i] = 0x22
	{
		size, err := m.AuthorityRent.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintNameservice(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	n9, err9 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.RecordRentDuration, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.RecordRentDuration):])
	if err9 != nil {
		return 0, err9
	}
	i -= n9
	i = encodeVarintNameservice(dAtA, i, uint64(n9))
	i--
	dAtA[i] = 0x12
	{
		size, err := m.RecordRent.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintNameservice(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Record) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Record) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Record) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Attributes) > 0 {
		i -= len(m.Attributes)
		copy(dAtA[i:], m.Attributes)
		i = encodeVarintNameservice(dAtA, i, uint64(len(m.Attributes)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Owners) > 0 {
		for iNdEx := len(m.Owners) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Owners[iNdEx])
			copy(dAtA[i:], m.Owners[iNdEx])
			i = encodeVarintNameservice(dAtA, i, uint64(len(m.Owners[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.Deleted {
		i--
		if m.Deleted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	n11, err11 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.ExpiryTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.ExpiryTime):])
	if err11 != nil {
		return 0, err11
	}
	i -= n11
	i = encodeVarintNameservice(dAtA, i, uint64(n11))
	i--
	dAtA[i] = 0x22
	n12, err12 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CreateTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CreateTime):])
	if err12 != nil {
		return 0, err12
	}
	i -= n12
	i = encodeVarintNameservice(dAtA, i, uint64(n12))
	i--
	dAtA[i] = 0x1a
	if len(m.BondId) > 0 {
		i -= len(m.BondId)
		copy(dAtA[i:], m.BondId)
		i = encodeVarintNameservice(dAtA, i, uint64(len(m.BondId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintNameservice(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AuthorityEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuthorityEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuthorityEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Record != nil {
		{
			size, err := m.Record.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintNameservice(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintNameservice(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NameAuthority) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NameAuthority) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NameAuthority) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n14, err14 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.ExpiryTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.ExpiryTime):])
	if err14 != nil {
		return 0, err14
	}
	i -= n14
	i = encodeVarintNameservice(dAtA, i, uint64(n14))
	i--
	dAtA[i] = 0x3a
	if len(m.BondId) > 0 {
		i -= len(m.BondId)
		copy(dAtA[i:], m.BondId)
		i = encodeVarintNameservice(dAtA, i, uint64(len(m.BondId)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.AuctionId) > 0 {
		i -= len(m.AuctionId)
		copy(dAtA[i:], m.AuctionId)
		i = encodeVarintNameservice(dAtA, i, uint64(len(m.AuctionId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintNameservice(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x22
	}
	if m.Height != 0 {
		i = encodeVarintNameservice(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x18
	}
	if len(m.OwnerAddress) > 0 {
		i -= len(m.OwnerAddress)
		copy(dAtA[i:], m.OwnerAddress)
		i = encodeVarintNameservice(dAtA, i, uint64(len(m.OwnerAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OwnerPublicKey) > 0 {
		i -= len(m.OwnerPublicKey)
		copy(dAtA[i:], m.OwnerPublicKey)
		i = encodeVarintNameservice(dAtA, i, uint64(len(m.OwnerPublicKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NameEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NameEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NameEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Record != nil {
		{
			size, err := m.Record.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintNameservice(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintNameservice(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NameRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NameRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NameRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.History) > 0 {
		for iNdEx := len(m.History) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.History[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintNameservice(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Latest != nil {
		{
			size, err := m.Latest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintNameservice(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NameRecordEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NameRecordEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NameRecordEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintNameservice(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintNameservice(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Signature) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Signature) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Signature) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PubKey) > 0 {
		i -= len(m.PubKey)
		copy(dAtA[i:], m.PubKey)
		i = encodeVarintNameservice(dAtA, i, uint64(len(m.PubKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sig) > 0 {
		i -= len(m.Sig)
		copy(dAtA[i:], m.Sig)
		i = encodeVarintNameservice(dAtA, i, uint64(len(m.Sig)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintNameservice(dAtA []byte, offset int, v uint64) int {
	offset -= sovNameservice(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.RecordRent.Size()
	n += 1 + l + sovNameservice(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.RecordRentDuration)
	n += 1 + l + sovNameservice(uint64(l))
	l = m.AuthorityRent.Size()
	n += 1 + l + sovNameservice(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.AuthorityRentDuration)
	n += 1 + l + sovNameservice(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.AuthorityGracePeriod)
	n += 1 + l + sovNameservice(uint64(l))
	if m.AuthorityAuctionEnabled {
		n += 2
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.AuthorityAuctionCommitsDuration)
	n += 1 + l + sovNameservice(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.AuthorityAuctionRevealsDuration)
	n += 1 + l + sovNameservice(uint64(l))
	l = m.AuthorityAuctionCommitFee.Size()
	n += 1 + l + sovNameservice(uint64(l))
	l = m.AuthorityAuctionRevealFee.Size()
	n += 1 + l + sovNameservice(uint64(l))
	l = m.AuthorityAuctionMinimumBid.Size()
	n += 1 + l + sovNameservice(uint64(l))
	return n
}

func (m *Record) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovNameservice(uint64(l))
	}
	l = len(m.BondId)
	if l > 0 {
		n += 1 + l + sovNameservice(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CreateTime)
	n += 1 + l + sovNameservice(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.ExpiryTime)
	n += 1 + l + sovNameservice(uint64(l))
	if m.Deleted {
		n += 2
	}
	if len(m.Owners) > 0 {
		for _, s := range m.Owners {
			l = len(s)
			n += 1 + l + sovNameservice(uint64(l))
		}
	}
	l = len(m.Attributes)
	if l > 0 {
		n += 1 + l + sovNameservice(uint64(l))
	}
	return n
}

func (m *AuthorityEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovNameservice(uint64(l))
	}
	if m.Record != nil {
		l = m.Record.Size()
		n += 1 + l + sovNameservice(uint64(l))
	}
	return n
}

func (m *NameAuthority) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OwnerPublicKey)
	if l > 0 {
		n += 1 + l + sovNameservice(uint64(l))
	}
	l = len(m.OwnerAddress)
	if l > 0 {
		n += 1 + l + sovNameservice(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovNameservice(uint64(m.Height))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovNameservice(uint64(l))
	}
	l = len(m.AuctionId)
	if l > 0 {
		n += 1 + l + sovNameservice(uint64(l))
	}
	l = len(m.BondId)
	if l > 0 {
		n += 1 + l + sovNameservice(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.ExpiryTime)
	n += 1 + l + sovNameservice(uint64(l))
	return n
}

func (m *NameEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovNameservice(uint64(l))
	}
	if m.Record != nil {
		l = m.Record.Size()
		n += 1 + l + sovNameservice(uint64(l))
	}
	return n
}

func (m *NameRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Latest != nil {
		l = m.Latest.Size()
		n += 1 + l + sovNameservice(uint64(l))
	}
	if len(m.History) > 0 {
		for _, e := range m.History {
			l = e.Size()
			n += 1 + l + sovNameservice(uint64(l))
		}
	}
	return n
}

func (m *NameRecordEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovNameservice(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovNameservice(uint64(m.Height))
	}
	return n
}

func (m *Signature) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sig)
	if l > 0 {
		n += 1 + l + sovNameservice(uint64(l))
	}
	l = len(m.PubKey)
	if l > 0 {
		n += 1 + l + sovNameservice(uint64(l))
	}
	return n
}

func sovNameservice(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNameservice(x uint64) (n int) {
	return sovNameservice(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNameservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordRent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RecordRent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordRentDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.RecordRentDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorityRent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AuthorityRent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorityRentDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.AuthorityRentDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorityGracePeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.AuthorityGracePeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorityAuctionEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AuthorityAuctionEnabled = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorityAuctionCommitsDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.AuthorityAuctionCommitsDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorityAuctionRevealsDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.AuthorityAuctionRevealsDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorityAuctionCommitFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AuthorityAuctionCommitFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorityAuctionRevealFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AuthorityAuctionRevealFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorityAuctionMinimumBid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AuthorityAuctionMinimumBid.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNameservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNameservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Record) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNameservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Record: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Record: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CreateTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.ExpiryTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deleted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Deleted = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owners", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owners = append(m.Owners, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attributes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attributes = append(m.Attributes[:0], dAtA[iNdEx:postIndex]...)
			if m.Attributes == nil {
				m.Attributes = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNameservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNameservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuthorityEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNameservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthorityEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthorityEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Record", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Record == nil {
				m.Record = &NameAuthority{}
			}
			if err := m.Record.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNameservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNameservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NameAuthority) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNameservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NameAuthority: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NameAuthority: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerPublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerPublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuctionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.ExpiryTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNameservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNameservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NameEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNameservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NameEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NameEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Record", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Record == nil {
				m.Record = &NameRecord{}
			}
			if err := m.Record.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNameservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNameservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NameRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNameservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NameRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NameRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Latest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Latest == nil {
				m.Latest = &NameRecordEntry{}
			}
			if err := m.Latest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field History", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.History = append(m.History, &NameRecordEntry{})
			if err := m.History[len(m.History)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNameservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNameservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NameRecordEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNameservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NameRecordEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NameRecordEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNameservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNameservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Signature) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNameservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Signature: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Signature: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sig", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sig = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNameservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNameservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNameservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNameservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNameservice(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNameservice
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNameservice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNameservice
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNameservice
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNameservice
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNameservice        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNameservice          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNameservice = fmt.Errorf("proto: unexpected end of group")
)
